@startuml

!theme plain
hide circle
skinparam linetype ortho
skinparam entity {
  BackgroundColor White
  BorderColor Black
  FontName "Consolas"
}

entity "Car" as Car {
  *car_id : INTEGER <<PK>>
  --
  brand : TEXT
  model : TEXT
  year : INTEGER
  price_per_day : INT
  is_busy : BOOLEAN
}

entity "Customer" as Customer {
  *customer_id : INTEGER <<PK>>
  --
  username : TEXT
  password : TEXT
  phone : TEXT
  email : TEXT
}

entity "Admin" as Admin {
  *admin_id : INTEGER <<PK>>
  --
  username : TEXT
  password : TEXT
}

entity "Rental" as Rental {
  *rental_id : INTEGER <<PK>>
  --
  car_id : INTEGER <<FK>>
  customer_id : INTEGER <<FK>>
  admin_id : INTEGER <<FK>>
  start_date : TEXT
  end_date : TEXT
  application_status : TEXT
  total_price : INT
}

entity "Payment" as Payment {
  *payment_id : INTEGER <<PK>>
  --
  rental_id : INTEGER <<FK>>
  amount : INT
  payment_date : TEXT
}

entity "Maintenance" as Maintenance {
  *id : INTEGER <<PK>>
  --
  car_id : INTEGER <<FK>>
  service_date : TEXT
  description : TEXT
  cost : INT
}

' СВЯЗИ (1:N и M:N)

' 1:N — Клиент может иметь несколько аренд
Customer ||--o{ Rental

' 1:N — Машина может участвовать в нескольких арендах
Car ||--o{ Rental

' 1:N — Администратор может подтверждать несколько аренд
Admin ||--o{ Rental

' 1:1 — Каждая аренда имеет один платёж
Rental ||--|| Payment

' 1:N — Одна машина может иметь несколько записей обслуживания
Car ||--o{ Maintenance

@enduml
